### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException

### ISSUE THREAD

**Issue by WallyCZ** [WallyCZ/PoGo-UWP#2]
Newtonsoft.Json.JsonSerializationException occurred
  HResult=-2146233088
  Message=Cannot create and populate list type Google.Protobuf.ByteString. Path 'PokemonCaughtByType', line 1, position 471.
  Source=Newtonsoft.Json
  StackTrace:
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(JsonReader reader, JsonArrayContract contract, Boolean& createdFromNonDefaultCreator)
  InnerException:

**Comment by Jehu147** [comment]
You the other time published a pre release from pogo 1.013 well what i want or I wonder that you published a new  prerelease to play a new version please
