### ISSUE TITLE
Prerelease

### ISSUE THREAD

**Issue by Jehu147** [WallyCZ/PoGo-UWP#3]
I want to test what the debe of pogo ar working could you gibe a release with a new version of pogo please

**Comment by Jehu147** [comment]
Please wally

**Comment by Jehu147** [comment]
I want it

**Comment by WallyCZ** [comment]
Please wait on official release

**Comment by Jehu147** [comment]
Ok thank you the have been shut down another time I hope the debe could crack it other time
